# Generated by Django 3.2 on 2021-05-05 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210505_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login_id',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role_Id',
            new_name='role_ID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirmpassword',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobilenumber',
        ),
    ]
